Features/event update tests
Forsee41/band-tracker-bot pull request #19
Opened 2023-08-10 23:03 UTC by Fanter99

2023-08-10 23:10 UTC, Fanter99 commented
Не так много кейсов с "invalid" fields. По сути только тикет к примеру None не может быть так как в дб это не nullable. Date и сэйлс отсеиваются в клиенте, там не может быть ничего invalid

2023-08-10 23:14 UTC, Fanter99 commented on band_tracker/db/dal.py
> +        match event.ticket_url:
с клиента может прилететь None
до этого тут просто str(None) бы было

2023-08-10 23:15 UTC, Fanter99 commented on band_tracker/db/dal.py
> +
с клиента может прилететь None.
до этого было бы просто str(None)

2023-08-10 23:21 UTC, Forsee41 requested changes

2023-08-10 23:21 UTC, Forsee41 commented on band_tracker/core/event.py
> +    async def get_artists(self, dal: DAL) -> list[Optional["Artist"]]:
я думаю тут не должно быть optional, какой смысл иметь несколько None в списке артистов
просто убрать все None, ну или как то иначе обработать их

2023-08-10 23:21 UTC, Forsee41 commented on band_tracker/db/dal.py
> +            socials_db = socials_db_result
тут просто socials_db = await artist_db.....
если конечно там сразу то что надо получается

2023-08-10 23:21 UTC, Forsee41 commented on tests/unit/db/test_add_event.py
> +        assert [i.name for i in result_artists if i is not None] == artists
тут всегда порядок выгрузки из бд будет соответствовать порядку инпут артистов? я делал через set(result) == set(input) на всякий случай, но мб и листы всегда сработают

2023-08-10 23:27 UTC, Fanter99 commented on band_tracker/db/dal.py
> +            socials_db = socials_db_result
ииииииииииищ

2023-08-10 23:41 UTC, Fanter99 commented on tests/unit/db/test_add_event.py
> +        assert [i.name for i in result_artists if i is not None] == artists
я щас разные комбинации попробовал, всё работает

2023-08-11 11:06 UTC, Forsee41 approved these changes

2023-08-11 11:07 UTC, merged