Iterator
Forsee41/band-tracker-bot pull request #24
Opened 2023-08-12 23:47 UTC by Fanter99

2023-08-13 00:18 UTC, Forsee41 requested changes

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +class CustomRequest(httpx.AsyncClient):
зач тут сабкласс, можно удалить

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                    return InvalidResponseStructureError(
тут можно конечно и через return, но вообще по идее должен быть raise. это asyncio.gather() автоматически "конвертирует" catch в ошибку как значение

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +        if not self.stop_flag:
тут чтобы не было вложенности, можно сделать так
if self.stop_flag:
    raise stopiteration
if not self.buffer........

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +            if not self.buffer:
если я правильно понимаю, тут эта ветка никогда не может не выполниться

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +            self.rate_count = 0
я так и не понял че за rate_count и зач он нужен, он на каждой итерации обнуляется

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                            return UnexpectedFaultResponseError("Bruh")
потом в логфайле ниче не поймешь с таким месседжем

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/errors.py
> +class InvalidResponseStructureError(Exception):
тут можно добавить филд json и в него складывать json, и на основе него генерировать текстовую репрезентацию ошибки, но это не обяз

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                                "Unexpected Error, fault tstring not found in response"
typo

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                self.buffer.append(await self.client.make_request(self.page_number))
имей в виду что это асинхронная функция, в этом месте (где await) может произойти свитч на другую такую. И потом может продолжить выполняться сначала функция с page_number 5, а только потом с 4. Это я к тому, что  у тебя может выполниться например page5, а потом произойти запрос к page4 и вылезти quota_violation, и после этого у тебя уменьшится page_number до 5, произойдет повторный запрос к 5, а 4 так и не будет зафетчен

2023-08-13 00:18 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                        case "policies.ratelimit.QuotaViolation":
мб тут стоит добавить sleep, но это еще одна возможность для свитча активных корутин

2023-08-13 10:12 UTC, Fanter99 commented on band_tracker/updater/iterator.py
> +            self.rate_count = 0
i forgot to put a recursion call

2023-08-13 11:15 UTC, Fanter99 commented on band_tracker/updater/iterator.py
> +                            return await self.__anext__()
return page_number to Updater, maybe it can handle it somehow.

2023-08-13 11:29 UTC, Forsee41 requested changes

2023-08-13 11:29 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +class PageIterator(AsyncIterator):
тут тоже не нужно наследование. Если ругается тайп чекер, можно добавить __aiter__, который будет возвращать self

2023-08-13 11:29 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                            self.page_number -= 1
я до сих пор думаю что нельзя использовать self.page_number.
можно сделать так
```python
async def __anext__(self) .....:
    current_page = self.page_number
    ....
    ....
    
    case "ratelimit error":
        ....
        self.page_number = current_page - 1

2023-08-13 11:29 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +        self.rate_count = 0
тут должен быть rate_limit_error_count, если я правильно понимаю

2023-08-13 11:29 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                        await asyncio.sleep(1)
надо еще подумать, должен ли тут быть sleep, или это логика вызывающего кода. Эти корутины выполняются чанками по 4 штуки, поэтому каждая "попробует" сделать запрос, уткнется в ratelimit и уйдет в sleep, не уверен что это лучший вариант

2023-08-13 11:29 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                            self.page_number -= 1
еще кстати думаю надо так сделать
```python
if current_page - 1 < self.page_number:
    self.page_number = current_page - 1
````
потому что у тебя сразу несколько корутин могут уткнуться в ratelimit, например 3 штуки, с 10, 11 и 12 page. Тогда может сначала 10 поставить page_number на 9, потом 11 на 10, и потом 12 на 11. По итогу page_number будет 11, хотя все 3, начиная с 10, не были получены

2023-08-13 11:32 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                        await asyncio.sleep(1)
еще кста ты уверен что quotaViolation это то, что вернется при превышении секундного лимита, а не только суточного?

2023-08-13 12:14 UTC, Forsee41 requested changes

2023-08-13 12:14 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +        self.page_number += 1
если заспаунить пачку запросов разом, то будет выполняться self.client.make_request с одним и тем же page number. 
```python
current_page = self.page_number
self.page_number += 1
make_request(current_page)
```
думаю так пофиксится, но это не точно. проверь тут логику

2023-08-13 12:14 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                    case "policies.ratelimit.QuotaViolation":
точно ли QuotaViolation на секундную квоту

2023-08-13 12:14 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +        data = self.buffer.pop(0)
тут возможно произойдет pop не той страницы, на которую делался запрос. Хотя скорее всего все норм, т.к. между append и pop нет await. Мб просто убрать буфер на всякий случай? он вроде бы нигде особо не используется, но может породить подобные баги

2023-08-13 12:14 UTC, Forsee41 commented on band_tracker/updater/iterator.py
> +                            return await self.__anext__()
проверь еще раз, не может ли тут вызваться anext для другого page number и если может, то ли что это нам нужно

2023-08-14 14:18 UTC, Fanter99 commented on band_tracker/updater/errors.py
> +
Это как раз дневная квота, её в апдейтере только смысл хэндлить имеет, так что вот еррор код тебе

2023-08-14 14:54 UTC, Forsee41 approved these changes
lgtm!

2023-08-14 14:55 UTC, merged