docker and compose files (dev version)
Forsee41/band-tracker-bot pull request #4
Opened 2023-07-04 23:16 UTC by Fanter99

2023-07-04 23:20 UTC, Fanter99 commented
я там замаунтил полностью проектную директорию в контейнер, чтобы не ребилдить имедж каждый раз, когда код меняется. Маунт в app/data для будущего persistence бота

2023-07-05 11:34 UTC, Forsee41 requested changes

2023-07-05 11:34 UTC, Forsee41 commented on .dockerignore
> -.env
.env не нужен в проде. В проде и в ci env vars прокидываются через docker-compose, в деве не нужен контейнер для запуска аппа

2023-07-05 11:34 UTC, Forsee41 commented on Dockerfile
> +FROM python:3.10
python3.11 на четверть быстрее

2023-07-05 11:34 UTC, Forsee41 commented on Dockerfile
> +RUN pip install --no-cache-dir -r requirements.txt
имедж собирается по слоям. Имеет смысл сначала установить requirements, и потом копировать сорсы проекта. Таким образом при обновлении кода все зависимости будут браться из кеша, их не нужно будет пересобирать

2023-07-05 11:34 UTC, Forsee41 commented on docker-compose.yml
> +      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
тестовая дб в отдельном контейнере. Если этот маунт не нужен для работы postgres контейнера, то его лучше убрать

2023-07-05 13:36 UTC, Forsee41 approved these changes

2023-07-05 13:36 UTC, merged