Better env loading
Forsee41/band-tracker-bot pull request #66
Opened 2023-12-26 03:54 UTC by Forsee41

Refactored Makefile
Makefile / docker compose files are now using env vars instead of hardcoded values
Also renamed container names, added band_tracker prefix to avoid name conflicts with other projects

2024-01-01 19:29 UTC, Fanter99 requested changes

2024-01-01 19:29 UTC, Fanter99 commented on migrations/versions/82c72be5643a_.py
empty revision

2024-01-02 09:30 UTC, Forsee41 commented on migrations/versions/82c72be5643a_.py
thats merge revision

2024-01-02 09:36 UTC, Fanter99 approved these changes

2024-01-02 09:36 UTC, merged