client features
Forsee41/band-tracker-bot pull request #9
Opened 2023-07-08 22:31 UTC by Fanter99

2023-07-08 22:51 UTC, Fanter99 commented on band_tracker/db/dal.py
> +            upcoming_events_count=0
тут пришлось закостылить. Там постгресс ошибку выдавал, что поле с апкаминг ивент пустое, я не стал разбираться.

2023-07-09 04:06 UTC, Forsee41 requested changes

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/core/artist.py
> +    socials: dict[str, Optional[HttpUrl]]
вместо Optional лучше использовать HttpUrl | None, так можно с python3.10

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/core/artist.py
> +    tickets_link: HttpUrl = Field(None)
None field в строгом HttpUrl поле. Если ticktes_link обязательное поле, то нужно убрать дефолт

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/core/artist.py
> +    images: list[HttpUrl] = Field(None)
дефолтное значение не None, a Field([])

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/core/event.py
> +    date: datetime = Field(None)
убрать дефолтный None для обязательного поля

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/core/event.py
> +    ticket_url: HttpUrl = Field(None)
тут тоже

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/core/event.py
> +    venue_country: StrictStr = Field(None)
тут если эти поля всегда будут, то убрать дефолт, если не всегда - сделать SrictStr | None

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/db/dal.py
> +            upcoming_events_count=0
я это у себя уже поправил, когда мерджить буду уберу

2023-07-09 04:06 UTC, Forsee41 commented on band_tracker/core/artist.py
> +    socials: dict[str, Optional[HttpUrl]]
Еще я думаю вместо None лучше использовать {} как дефолт, т.к. к у пустого дикта можно проверить наличие поля, а None придется разбирать как отдельный случай.
Мб вместо простого dict больше подойдет TypedDict, т.к. мы заранее знаем, какие именно там могут быть поля

2023-07-09 04:25 UTC, Forsee41 requested changes

2023-07-09 04:25 UTC, Forsee41 commented on band_tracker/ticketmaster/client.py
> +                        classification.get("genre", {}).get("name"),
если у genre или subgenre нет поля name, то будут сраться None

2023-07-09 10:38 UTC, Fanter99 commented on band_tracker/core/event.py
> +    ticket_url: HttpUrl = Field(None)
не уверен, что оно обязательное. Его может и не быть там спокойно. Просто с названием, если у нас и названия не будет у ивента/артиста, то значит все вообще по пизде пошло или этот энтити не имеет смысла

2023-07-09 10:42 UTC, Fanter99 commented on band_tracker/ticketmaster/client.py
> +                        classification.get("genre", {}).get("name"),
ну и чё

2023-07-09 10:45 UTC, Fanter99 commented on band_tracker/core/artist.py
> +    socials: dict[str, Optional[HttpUrl]]
ок

2023-07-09 10:47 UTC, Fanter99 commented on band_tracker/core/event.py
> +    date: datetime = Field(None)
пускай тоже необязательным будет

2023-07-09 11:16 UTC, Fanter99 commented on band_tracker/ticketmaster/client.py
> +                        classification.get("genre", {}).get("name"),
исправил

2023-07-09 11:18 UTC, Forsee41 commented on band_tracker/ticketmaster/client.py
> +                        classification.get("genre", {}).get("name"),
вообще целиком genres лучше делать пустым диктом, а не None, если там ничего нет, по той же причине, что и до этого там с чем то было, на None нужно будет отдельно делать проверки, а по пустому листу можно так же проитерироваться как и по листу с элементами
А иметь None как жанр вообще не имеет смысла, его лучше просто убрать. Ты же не будешь в бд добавлять жанр None

2023-07-09 11:20 UTC, Forsee41 approved these changes
You are making the world a better place by commiting these beautiful changes in this repo

2023-07-09 11:24 UTC, merged